DROP DATABASE IF EXISTS POJO_RENTING;
CREATE DATABASE IF NOT EXISTS POJO_RENTING;
USE POJO_RENTING;

CREATE TABLE SEDE(
	ID INT UNSIGNED	ZEROFILL NOT NULL AUTO_INCREMENT,
    CIUDAD VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID)
    
)ENGINE = INNODB;

CREATE TABLE CLIENTE(
	ID INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	NOMBRE VARCHAR(30) NOT NULL ,
	TELEFONO VARCHAR(12) NOT NULL ,
	EMAIL VARCHAR(30) NOT NULL ,
	PRIMARY KEY(ID),
	UNIQUE (NOMBRE)
) ENGINE = INNODB;

CREATE TABLE PARTICULAR(
	ID INT UNSIGNED ZEROFILL NOT NULL,
	DNI CHAR(9) NOT NULL,
	EDAD INT NOT NULL,
	PUNTOS INT NOT NULL,
	PRIMARY KEY(ID),
    CONSTRAINT FK1_CLIENTE
		FOREIGN KEY (ID) REFERENCES CLIENTE (ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK1_CLIENTE(ID)
)ENGINE = INNODB;

CREATE TABLE EMPRESA(
	ID INT UNSIGNED ZEROFILL NOT NULL,
	CIF CHAR(9) NOT NULL,
	N_ALQUILERES INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
    CONSTRAINT FK2_CLIENTE
		FOREIGN KEY (ID) REFERENCES CLIENTE (ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK2_CLIENTE(ID)
)ENGINE = INNODB;

CREATE TABLE COCHE(
	ID INT UNSIGNED	ZEROFILL NOT NULL AUTO_INCREMENT,
    ID_SEDE INT UNSIGNED ZEROFILL NOT NULL,
	MODELO VARCHAR(30) NOT NULL,
    MARCA VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK1_SEDE
		FOREIGN KEY (ID_SEDE) REFERENCES SEDE(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK1_SEDE(ID_SEDE)
)ENGINE = INNODB;

CREATE TABLE ALQUILER(
	ID INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT UNSIGNED ZEROFILL NOT NULL,
    ID_COCHE INT UNSIGNED ZEROFILL NOT NULL,
	FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRECIO_TOTAL FLOAT NOT NULL,
	DESCUENTO FLOAT NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK3_CLIENTE
		FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	
    CONSTRAINT FK1_COCHE
		FOREIGN KEY (ID_COCHE) REFERENCES COCHE(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK3_CLIENTE(ID_CLIENTE),
    INDEX FK1_COCHE(ID_COCHE)
)ENGINE = INNODB;

CREATE TABLE LARGO_PLAZO(
	ID INT UNSIGNED ZEROFILL NOT NULL,
    PRIMARY KEY(ID),
	CONSTRAINT FK1_ALQUILER
		FOREIGN KEY (ID) REFERENCES ALQUILER (ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK1_ALQUILER(ID)
)ENGINE = INNODB;

CREATE TABLE RESERVA(
	ID INT UNSIGNED	ZEROFILL NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT UNSIGNED ZEROFILL NOT NULL,
    ID_COCHE INT UNSIGNED ZEROFILL NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRIMARY KEY(ID),
    CONSTRAINT FK4_CLIENTE
		FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	CONSTRAINT FK2_COCHE
		FOREIGN KEY (ID_COCHE) REFERENCES COCHE(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK3_CLIENTE(ID_CLIENTE),
    INDEX FK2_COCHE(ID_COCHE)
    
    
)ENGINE = INNODB;