DROP DATABASE IF EXISTS POJO_RENTING;
CREATE DATABASE IF NOT EXISTS POJO_RENTING;
USE POJO_RENTING;
/**
CREATE TABLE SEDES(
	ID INT(5) UNSIGNED	ZEROFILL NOT NULL AUTO_INCREMENT,
    CIUDAD VARCHAR(30) NOT NULL,
    PRIMARY KEY(ID)
    
)ENGINE = INNODB;
**/
CREATE TABLE CLIENTES(
	ID INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
	TELEFONO VARCHAR(12) NOT NULL ,
	EMAIL VARCHAR(30) NOT NULL ,
	PRIMARY KEY(ID)
) ENGINE = INNODB;

CREATE TABLE PARTICULARES(
	ID INT(5) UNSIGNED ZEROFILL NOT NULL,
    	NOMBRE VARCHAR(15) NOT NULL,
    	APELLIDOS VARCHAR(25) NOT NULL,
	DNI CHAR(9) NOT NULL,
	EDAD INT NOT NULL,
	PUNTOS INT NOT NULL,
	FECHANAC DATE NOT NULL,
	PRIMARY KEY(ID),
    CONSTRAINT FK1_CLIENTES
		FOREIGN KEY (ID) REFERENCES CLIENTES(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK1_CLIENTES(ID),
    UNIQUE (NOMBRE, APELLIDOS)
)ENGINE = INNODB;

CREATE TABLE EMPRESAS(
	ID INT(5) UNSIGNED ZEROFILL NOT NULL,
    NOMBRE VARCHAR(30),
	CIF CHAR(10) NOT NULL,
	N_ALQUILERES INT UNSIGNED NOT NULL,
	PRIMARY KEY(ID),
    CONSTRAINT FK2_CLIENTES
		FOREIGN KEY (ID) REFERENCES CLIENTES (ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK2_CLIENTES(ID),
    UNIQUE (NOMBRE)
)ENGINE = INNODB;

CREATE TABLE COCHES(
	MATRICULA CHAR(7),
    -- ID_SEDE INT UNSIGNED ZEROFILL NOT NULL,
    ANHOS INT(2) UNSIGNED,
	MODELO VARCHAR(30) NOT NULL,
    ESTADO VARCHAR(20) NOT NULL,
    MARCA VARCHAR(30) NOT NULL,
    FECHA_M DATE NOT NULL,
    PRECIO_DIA FLOAT NOT NULL,
    PRIMARY KEY(MATRICULA)
    /**CONSTRAINT FK1_SEDE
		FOREIGN KEY (ID_SEDE) REFERENCES SEDES(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK1_SEDES(ID_SEDE)**/
)ENGINE = INNODB;

CREATE TABLE ALQUILERES(
	CODIGO INT(5) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT(5) UNSIGNED ZEROFILL NOT NULL,
	MATRICULA CHAR(7),
	FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRECIO_TOTAL FLOAT NOT NULL,
	DESCUENTO FLOAT NOT NULL,
    PRIMARY KEY(CODIGO),
    CONSTRAINT FK3_CLIENTES
		FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	
    CONSTRAINT FK1_COCHE
		FOREIGN KEY (MATRICULA) REFERENCES COCHES(MATRICULA)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK3_CLIENTES(ID_CLIENTE),
    INDEX FK1_COCHES(MATRICULA)
)ENGINE = INNODB;

CREATE TABLE LARGO_PLAZO(
	CODIGO INT(5) UNSIGNED ZEROFILL NOT NULL,
    PRIMARY KEY(CODIGO),
	CONSTRAINT FK1_ALQUILER
		FOREIGN KEY (CODIGO) REFERENCES ALQUILERES(CODIGO)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK1_ALQUILERES(CODIGO)
)ENGINE = INNODB;

CREATE TABLE RESERVAS(
	CODIGO INT(5) UNSIGNED	ZEROFILL NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT(5) UNSIGNED ZEROFILL NOT NULL,
	MATRICULA CHAR(7),
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRIMARY KEY(CODIGO),
    CONSTRAINT FK4_CLIENTE
		FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	CONSTRAINT FK2_COCHE
		FOREIGN KEY (MATRICULA) REFERENCES COCHES(MATRICULA)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	INDEX FK3_CLIENTES(ID_CLIENTE),
    INDEX FK2_COCHES(MATRICULA)
    
    
)ENGINE = INNODB;
