/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import hibernate.NewHibernateUtil;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import org.hibernate.Session;
import pojos.Cliente;
import pojos.Coche;
import pojos.Empresa;
import pojos.Particular;

/**
 *
 * @author a18carlosva
 */
public class Alquileres extends javax.swing.JPanel implements IClientesAlquileres, ICochesAlquileres{
    
    private JPanel panelMainClientes;
    private JPanel panelMainCoches;
    private JFrame aplicacion;
    
    /**
     * Creates new form Alquileres
     */
    public Alquileres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionCoche = new javax.swing.JDialog();
        seleccionCliente = new javax.swing.JDialog();
        panelDatosClientes = new javax.swing.JPanel();
        lblDni = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnAlta = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        entEstado = new javax.swing.JTextField();
        entMarca = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        entModelo = new javax.swing.JTextField();
        btnSeleccionarCliente = new javax.swing.JButton();
        btnSeleccionarCoche = new javax.swing.JButton();
        entModelo1 = new javax.swing.JTextField();
        window = new javax.swing.JPanel();

        seleccionCoche.setSize(new java.awt.Dimension(809, 606));

        seleccionCliente.setSize(new java.awt.Dimension(809, 606));

        panelDatosClientes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(0, 0, 0)));

        lblDni.setText("Fecha Inicio");

        lblTelefono.setText("Fecha Final");

        btnAlta.setText("ALTA");

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnSeleccionarCliente.setText("Selec Cliente");
        btnSeleccionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarClienteActionPerformed(evt);
            }
        });

        btnSeleccionarCoche.setText("Selec Coche");
        btnSeleccionarCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDatosClientesLayout = new javax.swing.GroupLayout(panelDatosClientes);
        panelDatosClientes.setLayout(panelDatosClientesLayout);
        panelDatosClientesLayout.setHorizontalGroup(
            panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(panelDatosClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAlta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDatosClientesLayout.createSequentialGroup()
                        .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDatosClientesLayout.createSequentialGroup()
                                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTelefono)
                                    .addComponent(btnSeleccionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnSeleccionarCoche, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblDni, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(entModelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                    .addComponent(entEstado, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entModelo1)))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDatosClientesLayout.setVerticalGroup(
            panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClientesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSeleccionarCliente)
                    .addComponent(entModelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeleccionarCoche))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDni))
                .addGap(18, 18, 18)
                .addGroup(panelDatosClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(entMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefono))
                .addGap(30, 30, 30)
                .addComponent(btnAlta)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addContainerGap(316, Short.MAX_VALUE))
        );

        window.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelDatosClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(window, javax.swing.GroupLayout.DEFAULT_SIZE, 841, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDatosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(window, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSeleccionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarClienteActionPerformed
        listarClientes(); //Listo los clientes en el dialogo
        seleccionCliente.setVisible(true); //Enseño el dialogo
    }//GEN-LAST:event_btnSeleccionarClienteActionPerformed

    private void btnSeleccionarCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarCocheActionPerformed
        listarCoches(); //Listo los clientes en el dialogo
        seleccionCoche.setVisible(true); //Enseño el dialogo
    }//GEN-LAST:event_btnSeleccionarCocheActionPerformed
    
    @Override
    public void listarClientes(){ //lista los clientes
        if(panelMainClientes != null){
            panelMainClientes.removeAll();
            panelMainClientes.revalidate();
            panelMainClientes.repaint();
            seleccionCliente.remove(panelMainClientes);
            seleccionCliente.revalidate();
            seleccionCliente.repaint();
        }

        panelMainClientes = new JPanel(new BorderLayout());
        seleccionCliente.add(panelMainClientes);
        GridBagLayout innerLayout = new GridBagLayout();
        GridBagConstraints innerConstraints = new GridBagConstraints();
        JPanel innerPanel = new JPanel(innerLayout);

        Session sesion = NewHibernateUtil.getSession();
        sesion.beginTransaction();
        List<Cliente> clientes = sesion.createCriteria(Cliente.class).list();//quitar esta linea
        int numeroClientes = clientes.size();
        int numeroIteracionesX = (numeroClientes/3)+1;
        int numeroIteracionesTotales = 0;

        innerConstraints.weightx = 0.5;
        innerConstraints.weighty = 0.5;
        innerConstraints.gridy = 0;

        for(int i = 0; i < numeroIteracionesX; i++){    
            for(int j = 0; j < 3; j++){
                if(numeroIteracionesTotales != numeroClientes){
                    Cliente cliente = clientes.get(numeroIteracionesTotales);
                    boxClientes boxCliente;
                    if(cliente instanceof Particular){
                        boxCliente = new boxClientes(((Particular)cliente).getNombre(), ((Particular)cliente).getDni());
                    }else{
                        boxCliente = new boxClientes(((Empresa)cliente).getNombre(), ((Empresa)cliente).getCif());
                    }
                    boxCliente.setPanelPadre(this);
                    boxCliente.setClienteRepresentado(cliente);
                    boxCliente.setCentrarEnDialogo(seleccionCliente);
                    boxCliente.getBtnSeleccionar().setVisible(true);
                    boxCliente.getBtnModCli().setVisible(false);
                    boxCliente.getBtnEliminar().setVisible(false);
                    innerConstraints.gridx = j;
                    innerConstraints.gridy = i;
                    innerPanel.add(boxCliente, innerConstraints);
                    numeroIteracionesTotales++;
                }else{
                    break;
                }
            }
        }

        JPanel innerVoidPanel = new JPanel();
        innerConstraints.weighty = 1.0;
        innerConstraints.fill = GridBagConstraints.VERTICAL;
        innerLayout.setConstraints(innerVoidPanel, innerConstraints);
        innerPanel.add(innerVoidPanel);

        //...

        JScrollPane scrollPanel = new JScrollPane(innerPanel);
        scrollPanel.getVerticalScrollBar().setUnitIncrement(16);
        panelMainClientes.add(scrollPanel, BorderLayout.CENTER);
        sesion.close();

    }
    
    @Override
    public void listarCoches(){
        if(panelMainCoches != null){
            panelMainCoches.removeAll();
            panelMainCoches.revalidate();
            panelMainCoches.repaint();
            seleccionCoche.remove(panelMainCoches);
            seleccionCoche.revalidate();
            seleccionCoche.repaint();
        }
        
        panelMainCoches = new JPanel(new BorderLayout());
        seleccionCoche.add(panelMainCoches);
        GridBagLayout innerLayout = new GridBagLayout();
        GridBagConstraints innerConstraints = new GridBagConstraints();
        JPanel innerPanel = new JPanel(innerLayout);
        
        Session sesion = NewHibernateUtil.getSession();
        sesion.beginTransaction();
        List<Coche> coches = sesion.createCriteria(Coche.class).list();
        int numeroCoches = coches.size();
        int numeroIteracionesX = (numeroCoches/3)+1;
        int numeroIteracionesTotales = 0;
        
        innerConstraints.weightx = 0.5;
        innerConstraints.weighty = 0.5;
        innerConstraints.gridy = 0;
        
        for(int i = 0; i < numeroIteracionesX; i++){    
            for(int j = 0; j < 3; j++){
                if(numeroIteracionesTotales != numeroCoches){
                    Coche coche = coches.get(numeroIteracionesTotales);
                    boxCoches boxCoches = new boxCoches(coche.getMatricula(), coche.getMarca(), coche.getModelo());
                    boxCoches.setPanelPadre(this);
                    boxCoches.setCocheRepresentado(coche);
                    boxCoches.getBtnModCoc().setVisible(false);
                    boxCoches.getBtnEliminar().setVisible(false);
                    boxCoches.getBtnSeleccionar().setVisible(true);
                    innerConstraints.gridx = j;
                    innerConstraints.gridy = i;
                    innerPanel.add(boxCoches, innerConstraints);
                    numeroIteracionesTotales++;
                }else{
                    break;
                }
            }
        }

        JPanel innerVoidPanel = new JPanel();
        innerConstraints.weighty = 1.0;
        innerConstraints.fill = GridBagConstraints.VERTICAL;
        innerLayout.setConstraints(innerVoidPanel, innerConstraints);
        innerPanel.add(innerVoidPanel);

        //...

        JScrollPane scrollPanel = new JScrollPane(innerPanel);
        scrollPanel.getVerticalScrollBar().setUnitIncrement(16);
        panelMainCoches.add(scrollPanel, BorderLayout.CENTER);
        sesion.getTransaction().commit();
        sesion.close();
    
    }

    public JFrame getAplicacion() {
        return aplicacion;
    }

    public void setAplicacion(JFrame aplicacion) {
        this.aplicacion = aplicacion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnSeleccionarCliente;
    private javax.swing.JButton btnSeleccionarCoche;
    private javax.swing.JTextField entEstado;
    private javax.swing.JTextField entMarca;
    private javax.swing.JTextField entModelo;
    private javax.swing.JTextField entModelo1;
    private javax.swing.JButton jButton4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JPanel panelDatosClientes;
    private javax.swing.JDialog seleccionCliente;
    private javax.swing.JDialog seleccionCoche;
    private javax.swing.JPanel window;
    // End of variables declaration//GEN-END:variables
}
