package paneles;

import hibernate.NewHibernateUtil;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import metodos.Modificar;
import org.hibernate.Session;
import pojos.Alquiler;
import pojos.Cliente;
import pojos.Empresa;
import pojos.Particular;

public class boxAlquileres extends javax.swing.JPanel {

    /**
     * Creates new form boxClientes
     */
    
    private Alquileres panelPadre = null;
    private boxClientes panelPadreEnClientes = null;
    private Alquiler alquilerRepresentado;
    private JFrame aplicacion;
    private JDialog CentrarEnDialogo;

    public boxAlquileres(String dni, String matricula, int codigo) {
        initComponents();
        lblDniCif.setText(dni);
        lblMatricula.setText(matricula);
        lblCodigo.setText(String.valueOf(codigo));
        btnSeleccionar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoEliminar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        lblNombreEliminar = new javax.swing.JLabel();
        lblDigCodigo = new javax.swing.JLabel();
        lblTelfEliminar = new javax.swing.JLabel();
        lblDigCliente = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDigAceptar = new javax.swing.JButton();
        btnDigCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblEdadEliminar = new javax.swing.JLabel();
        lblDigCoche = new javax.swing.JLabel();
        lblPuntosEliminar = new javax.swing.JLabel();
        lblDigPrecio = new javax.swing.JLabel();
        lblDniEliminar = new javax.swing.JLabel();
        lblDigFechaI = new javax.swing.JLabel();
        lblEmailEliminar = new javax.swing.JLabel();
        lblDigFechaF = new javax.swing.JLabel();
        dialogoModificar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        lblModNombre = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnModAceptar = new javax.swing.JButton();
        btnDigCancelar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblModDni = new javax.swing.JLabel();
        lblModEmail = new javax.swing.JLabel();
        entModCodigo = new javax.swing.JTextField();
        entModFechaI = new javax.swing.JTextField();
        entModFechaF = new javax.swing.JTextField();
        dialogoDatos = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        lblNombreData = new javax.swing.JLabel();
        lblDataCodigo = new javax.swing.JLabel();
        lblTelfData = new javax.swing.JLabel();
        lblDataPrecio = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnDatosAceptar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblEdadData = new javax.swing.JLabel();
        lblDataCoche = new javax.swing.JLabel();
        lblPuntosData = new javax.swing.JLabel();
        lblDataFechaF = new javax.swing.JLabel();
        lblDniData = new javax.swing.JLabel();
        lblDataDescuento = new javax.swing.JLabel();
        lblEmailData = new javax.swing.JLabel();
        lblDataFechaI = new javax.swing.JLabel();
        lblApelData = new javax.swing.JLabel();
        lblDataCliente = new javax.swing.JLabel();
        boxCliente = new javax.swing.JPanel();
        lblVerCliente = new javax.swing.JLabel();
        lblVerCoche = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblDniCif = new javax.swing.JLabel();
        btnMod = new javax.swing.JButton();
        lblMatricula = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();
        lblCodigo = new javax.swing.JLabel();
        lblVerCodigo = new javax.swing.JLabel();

        dialogoEliminar.setTitle("ELIMINAR");
        dialogoEliminar.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoEliminar.setModal(true);
        dialogoEliminar.setResizable(false);
        dialogoEliminar.setSize(new java.awt.Dimension(416, 269));

        jLabel1.setText("DESEA ELIMINAR ESTE ALQUILER?");

        lblNombreEliminar.setText("Codigo");

        lblDigCodigo.setText("jLabel3");

        lblTelfEliminar.setText("Cliente");

        lblDigCliente.setText("jLabel3");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exclamation-mark.png"))); // NOI18N

        btnDigAceptar.setText("Aceptar");
        btnDigAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigAceptarActionPerformed(evt);
            }
        });

        btnDigCancelar.setText("Cancelar");
        btnDigCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigCancelarActionPerformed(evt);
            }
        });

        lblEdadEliminar.setText("Coche");

        lblDigCoche.setText("jLabel3");

        lblPuntosEliminar.setText("Precio");

        lblDigPrecio.setText("jLabel3");

        lblDniEliminar.setText("Fecha Inicio");

        lblDigFechaI.setText("jLabel3");

        lblEmailEliminar.setText("Fecha Fin");

        lblDigFechaF.setText("jLabel3");

        javax.swing.GroupLayout dialogoEliminarLayout = new javax.swing.GroupLayout(dialogoEliminar.getContentPane());
        dialogoEliminar.getContentPane().setLayout(dialogoEliminarLayout);
        dialogoEliminarLayout.setHorizontalGroup(
            dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialogoEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTelfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdadEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDigCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDniEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblEmailEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPuntosEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDigPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(60, 60, 60))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                                .addComponent(btnDigAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDigCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))))))
        );
        dialogoEliminarLayout.setVerticalGroup(
            dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoEliminarLayout.createSequentialGroup()
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigCodigo)
                    .addComponent(lblDniEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigFechaI))
                .addGap(0, 0, 0)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigCliente)
                    .addComponent(lblEmailEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigFechaF))
                .addGap(0, 0, 0)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEdadEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigCoche)
                    .addComponent(lblPuntosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigPrecio))
                .addGap(18, 18, 18)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigAceptar)
                    .addComponent(btnDigCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogoModificar.setTitle("MODIFICAR");
        dialogoModificar.setMinimumSize(new java.awt.Dimension(416, 299));
        dialogoModificar.setModal(true);
        dialogoModificar.setResizable(false);
        dialogoModificar.setSize(new java.awt.Dimension(462, 264));

        jLabel6.setText("MODIFICACIONES");

        lblModNombre.setText("Codigo");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/resume(1).png"))); // NOI18N

        btnModAceptar.setText("Aceptar");
        btnModAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAceptarActionPerformed(evt);
            }
        });

        btnDigCancelar1.setText("Cancelar");
        btnDigCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigCancelar1ActionPerformed(evt);
            }
        });

        lblModDni.setText("Fecha Inicio");

        lblModEmail.setText("Fecha fin");

        entModCodigo.setEditable(false);

        entModFechaI.setToolTipText("(dd/MM/yyyy)");

        entModFechaF.setToolTipText("(dd/MM/yyyy)");

        javax.swing.GroupLayout dialogoModificarLayout = new javax.swing.GroupLayout(dialogoModificar.getContentPane());
        dialogoModificar.getContentPane().setLayout(dialogoModificarLayout);
        dialogoModificarLayout.setHorizontalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addComponent(lblModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entModCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblModEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entModFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entModFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDigCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoModificarLayout.setVerticalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModDni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModFechaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModFechaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModAceptar)
                    .addComponent(btnDigCancelar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogoDatos.setTitle("DATOS");
        dialogoDatos.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoDatos.setModal(true);
        dialogoDatos.setResizable(false);
        dialogoDatos.setSize(new java.awt.Dimension(449, 329));

        jLabel7.setText("DATOS DEL ALQUILER");

        lblNombreData.setText("Codigo");

        lblDataCodigo.setText("jLabel3");

        lblTelfData.setText("Precio");

        lblDataPrecio.setText("jLabel3");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contact-form.png"))); // NOI18N

        btnDatosAceptar.setText("Aceptar");
        btnDatosAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAceptarActionPerformed(evt);
            }
        });

        lblEdadData.setText("Coche");

        lblDataCoche.setText("jLabel3");

        lblPuntosData.setText("Fecha fin");

        lblDataFechaF.setText("jLabel3");

        lblDniData.setText("Descuento");

        lblDataDescuento.setText("jLabel3");

        lblEmailData.setText("Fecha inicio");

        lblDataFechaI.setText("jLabel3");

        lblApelData.setText("Cliente");

        lblDataCliente.setText("jLabel3");

        javax.swing.GroupLayout dialogoDatosLayout = new javax.swing.GroupLayout(dialogoDatos.getContentPane());
        dialogoDatos.getContentPane().setLayout(dialogoDatosLayout);
        dialogoDatosLayout.setHorizontalGroup(
            dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEdadData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addComponent(lblApelData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addComponent(lblTelfData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDataPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDniData)
                    .addComponent(lblEmailData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPuntosData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDataFechaI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataDescuento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataFechaF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel18)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnDatosAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoDatosLayout.setVerticalGroup(
            dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataCoche)))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDniData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataDescuento))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFechaI)
                            .addComponent(lblApelData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataCliente))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntosData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFechaF))))
                .addGap(0, 0, 0)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelfData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataPrecio))
                .addGap(26, 26, 26)
                .addComponent(btnDatosAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        setBorder(new javax.swing.border.MatteBorder(null));

        boxCliente.setBorder(new javax.swing.border.MatteBorder(null));

        lblVerCliente.setText("Cliente");

        lblVerCoche.setText("Coche");

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/car-rent.png"))); // NOI18N

        btnDatos.setText("Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblDniCif.setText("lblDniCif");

        btnMod.setText("Modificar");
        btnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModActionPerformed(evt);
            }
        });

        lblMatricula.setText("lblMatricula");

        btnSeleccionar.setText("Seleccionar");

        lblCodigo.setText("lblCodigo");

        lblVerCodigo.setText("Codigo");

        javax.swing.GroupLayout boxClienteLayout = new javax.swing.GroupLayout(boxCliente);
        boxCliente.setLayout(boxClienteLayout);
        boxClienteLayout.setHorizontalGroup(
            boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxClienteLayout.createSequentialGroup()
                        .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblVerCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVerCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVerCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDniCif, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImg)
                .addGap(97, 97, 97))
        );
        boxClienteLayout.setVerticalGroup(
            boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDniCif, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVerCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar))
                    .addComponent(btnMod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        lblDataCodigo.setText(String.valueOf(alquilerRepresentado.getCodigo()));
        if (alquilerRepresentado.getParticular() != null) {
            lblDataCliente.setText(alquilerRepresentado.getParticular().getDni());
        } else {
            lblDataCliente.setText(alquilerRepresentado.getEmpresa().getCif());
        }
        lblDataCoche.setText(alquilerRepresentado.getCoche().getMatricula());
        lblDataPrecio.setText(String.valueOf(alquilerRepresentado.getPrecioTotal()));
        lblDataDescuento.setText(String.valueOf(alquilerRepresentado.getDescuento()));
        lblDataFechaI.setText(sdf.format(alquilerRepresentado.getFechaInicio()));
        lblDataFechaF.setText(sdf.format(alquilerRepresentado.getFechaFin()));
        dialogoDatos.setVisible(true);
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        lblDigCodigo.setText(String.valueOf(alquilerRepresentado.getCodigo()));
        lblDigCoche.setText(alquilerRepresentado.getCoche().getMatricula());
        if (alquilerRepresentado.getParticular() != null) {
            lblDigCliente.setText(alquilerRepresentado.getParticular().getDni());
        } else {
            lblDigCliente.setText(alquilerRepresentado.getEmpresa().getCif());
        }

        lblDigFechaI.setText(sdf.format(alquilerRepresentado.getFechaInicio()));
        lblDigFechaF.setText(sdf.format(alquilerRepresentado.getFechaFin()));
        lblDigPrecio.setText(String.valueOf(alquilerRepresentado.getPrecioTotal()));
        dialogoEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDigAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigAceptarActionPerformed
        Session sesion = NewHibernateUtil.getSession();
        sesion.beginTransaction();
        sesion.delete(alquilerRepresentado);
        sesion.getTransaction().commit();
        sesion.close();
        if(panelPadre != null){
            panelPadre.listarAlquileres();
        }else{
            panelPadreEnClientes.listarSusAlquileres();
        }
        dialogoEliminar.setVisible(false);
    }//GEN-LAST:event_btnDigAceptarActionPerformed

    private void btnDigCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigCancelarActionPerformed
        dialogoEliminar.setVisible(false);
    }//GEN-LAST:event_btnDigCancelarActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        entModCodigo.setText(String.valueOf(alquilerRepresentado.getCodigo()));
        entModFechaI.setText(sdf.format(alquilerRepresentado.getFechaInicio()));
        entModFechaF.setText(sdf.format(alquilerRepresentado.getFechaFin()));
        dialogoModificar.setVisible(true);
    }//GEN-LAST:event_btnModActionPerformed

    private void btnModAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAceptarActionPerformed
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date fechaI = sdf.parse(entModFechaI.getText());
            Date fechaF = sdf.parse(entModFechaF.getText());
            float precioTotal,
                    descuento = 0;
            int duracion = (int) ((fechaF.getTime() - fechaI.getTime()) / 86400000);
            entModCodigo.setText(String.valueOf(alquilerRepresentado.getCodigo()));
            alquilerRepresentado.setFechaInicio(fechaI);
            alquilerRepresentado.setFechaFin(fechaF);
            if (alquilerRepresentado.getParticular() != null) {
                if (alquilerRepresentado.getParticular().getPuntos() == 15) {
                    descuento = 0.1f;
                }
            }else{
                alquilerRepresentado.getEmpresa().setnAlquileres(alquilerRepresentado.getEmpresa().getnAlquileres() + 1);
                if (alquilerRepresentado.getEmpresa().getnAlquileres() > 100) {
                    descuento = 0.1f;
                }
            }
            if(duracion > 30 && duracion < 180){
                descuento = descuento + (0.1f);
            }else if(duracion >= 180 && duracion < 360){
                descuento = descuento + (0.2f);
            }else if(duracion >= 360 && duracion < 720){
                descuento = descuento + (0.3f);
            }else if(duracion >= 720){
                descuento = descuento + (0.4f);
            }
            float precioDia = alquilerRepresentado.getCoche().getPrecioDia();
            precioTotal =  precioDia * duracion * (1 - descuento);
            alquilerRepresentado.setPrecioTotal(precioTotal);
            Modificar.alquileres(alquilerRepresentado);
        } catch (ParseException pe) {
            System.out.println(pe);
        }
        if(panelPadre != null){
            panelPadre.listarAlquileres();
        }else{
            panelPadreEnClientes.listarSusAlquileres();
        }
        dialogoModificar.setVisible(false);
    }//GEN-LAST:event_btnModAceptarActionPerformed

    private void btnDigCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigCancelar1ActionPerformed
        dialogoModificar.setVisible(false);
    }//GEN-LAST:event_btnDigCancelar1ActionPerformed

    private void btnDatosAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAceptarActionPerformed
        dialogoDatos.setVisible(false);
    }//GEN-LAST:event_btnDatosAceptarActionPerformed

    public IClientesAlquileres getPanelPadre() {
        return panelPadre;
    }

    public void setPanelPadre(Alquileres panelPadre) {
        this.panelPadre = panelPadre;
    }

    public JFrame getAplicacion() {
        return aplicacion;
    }

    public void setAplicacion(JFrame aplicacion) {
        this.aplicacion = aplicacion;
        dialogoDatos.setLocationRelativeTo(aplicacion);
        dialogoEliminar.setLocationRelativeTo(aplicacion);
        dialogoModificar.setLocationRelativeTo(aplicacion);
    }

    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public void setBtnSeleccionar(JButton btnSeleccionar) {
        this.btnSeleccionar = btnSeleccionar;
    }

    public JButton getBtnDatos() {
        return btnDatos;
    }

    public void setBtnDatos(JButton btnDatos) {
        this.btnDatos = btnDatos;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnModCli() {
        return btnMod;
    }

    public void setBtnModCli(JButton btnModCli) {
        this.btnMod = btnModCli;
    }

    public JDialog getCentrarEnDialogo() {
        return CentrarEnDialogo;
    }

    public void setCentrarEnDialogo(JDialog CentrarEnDialogo) {
        this.CentrarEnDialogo = CentrarEnDialogo;
        dialogoDatos.setLocationRelativeTo(CentrarEnDialogo);
        dialogoEliminar.setLocationRelativeTo(CentrarEnDialogo);
        dialogoModificar.setLocationRelativeTo(CentrarEnDialogo);
    }

    public Alquiler getAlquilerRepresentado() {
        return alquilerRepresentado;
    }

    public void setAlquilerRepresentado(Alquiler alquilerRepresentado) {
        this.alquilerRepresentado = alquilerRepresentado;
    }

    public boxClientes getPanelPadreEnClientes() {
        return panelPadreEnClientes;
    }

    public void setPanelPadreEnClientes(boxClientes panelPadreEnClientes) {
        this.panelPadreEnClientes = panelPadreEnClientes;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCliente;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnDatosAceptar;
    private javax.swing.JButton btnDigAceptar;
    private javax.swing.JButton btnDigCancelar;
    private javax.swing.JButton btnDigCancelar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnMod;
    private javax.swing.JButton btnModAceptar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JDialog dialogoDatos;
    private javax.swing.JDialog dialogoEliminar;
    private javax.swing.JDialog dialogoModificar;
    private javax.swing.JTextField entModCodigo;
    private javax.swing.JTextField entModFechaF;
    private javax.swing.JTextField entModFechaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblApelData;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDataCliente;
    private javax.swing.JLabel lblDataCoche;
    private javax.swing.JLabel lblDataCodigo;
    private javax.swing.JLabel lblDataDescuento;
    private javax.swing.JLabel lblDataFechaF;
    private javax.swing.JLabel lblDataFechaI;
    private javax.swing.JLabel lblDataPrecio;
    private javax.swing.JLabel lblDigCliente;
    private javax.swing.JLabel lblDigCoche;
    private javax.swing.JLabel lblDigCodigo;
    private javax.swing.JLabel lblDigFechaF;
    private javax.swing.JLabel lblDigFechaI;
    private javax.swing.JLabel lblDigPrecio;
    private javax.swing.JLabel lblDniCif;
    private javax.swing.JLabel lblDniData;
    private javax.swing.JLabel lblDniEliminar;
    private javax.swing.JLabel lblEdadData;
    private javax.swing.JLabel lblEdadEliminar;
    private javax.swing.JLabel lblEmailData;
    private javax.swing.JLabel lblEmailEliminar;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModDni;
    private javax.swing.JLabel lblModEmail;
    private javax.swing.JLabel lblModNombre;
    private javax.swing.JLabel lblNombreData;
    private javax.swing.JLabel lblNombreEliminar;
    private javax.swing.JLabel lblPuntosData;
    private javax.swing.JLabel lblPuntosEliminar;
    private javax.swing.JLabel lblTelfData;
    private javax.swing.JLabel lblTelfEliminar;
    private javax.swing.JLabel lblVerCliente;
    private javax.swing.JLabel lblVerCoche;
    private javax.swing.JLabel lblVerCodigo;
    // End of variables declaration//GEN-END:variables
}
