package paneles;

import hibernate.NewHibernateUtil;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import metodos.Modificar;
import org.hibernate.Session;
import pojos.Coche;

public class boxCoches extends javax.swing.JPanel {

    /**
     * Creates new form boxClientes
     */
    
    private ICochesAlquileres panelPadre;
    private Coche cocheRepresentado;
    
    public boxCoches(String matricula, String marca, String modelo) {
        initComponents();
        lblMatricula.setText(matricula);
        lblMarca.setText(marca);
        lblModelo.setText(modelo);
        btnSeleccionar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoEliminar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDigMatricula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblDigMarca = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDigAceptar = new javax.swing.JButton();
        btnDigCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblDigModelo = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblDigPrecio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDigEstado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblDigAnos = new javax.swing.JLabel();
        dialogoModificar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        lblModMatricula = new javax.swing.JLabel();
        lblModModelo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnModAceptar = new javax.swing.JButton();
        btnDigCancelar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblModFecha = new javax.swing.JLabel();
        lblModPrecio = new javax.swing.JLabel();
        entModMatricula = new javax.swing.JTextField();
        entModFecha = new javax.swing.JTextField();
        entModModelo = new javax.swing.JTextField();
        entModPrecio = new javax.swing.JTextField();
        entModMarca = new javax.swing.JTextField();
        entModEstado = new javax.swing.JTextField();
        lblModMarca = new javax.swing.JLabel();
        lblModFechaNac = new javax.swing.JLabel();
        dialogoDatos = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        lblMatriculaData = new javax.swing.JLabel();
        lblDataMatricula = new javax.swing.JLabel();
        lblEstadoData = new javax.swing.JLabel();
        lblDataEstado = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnDatosAceptar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblModeloData = new javax.swing.JLabel();
        lblDataModelo = new javax.swing.JLabel();
        lblPrecioData = new javax.swing.JLabel();
        lblDataPrecio = new javax.swing.JLabel();
        lblFechaData = new javax.swing.JLabel();
        lblDataFecha = new javax.swing.JLabel();
        lblAnhosData = new javax.swing.JLabel();
        lblDataAnhos = new javax.swing.JLabel();
        lblmarcaData = new javax.swing.JLabel();
        lblDataMarca = new javax.swing.JLabel();
        boxCliente = new javax.swing.JPanel();
        lblMatriculaCoc = new javax.swing.JLabel();
        lblMarcaCoc = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblMatricula = new javax.swing.JLabel();
        btnModCoc = new javax.swing.JButton();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblModeloCoc = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        dialogoEliminar.setTitle("ELIMINAR");
        dialogoEliminar.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoEliminar.setModal(true);
        dialogoEliminar.setResizable(false);
        dialogoEliminar.setSize(new java.awt.Dimension(416, 299));

        jLabel1.setText("DESEA ELIMINAR EL COCHE?");

        jLabel2.setText("Matricula");

        lblDigMatricula.setText("jLabel3");

        jLabel4.setText("Marca");

        lblDigMarca.setText("jLabel3");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exclamation-mark.png"))); // NOI18N

        btnDigAceptar.setText("Aceptar");
        btnDigAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigAceptarActionPerformed(evt);
            }
        });

        btnDigCancelar.setText("Cancelar");
        btnDigCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Modelo");

        lblDigModelo.setText("jLabel3");

        jLabel15.setText("Precio día");

        lblDigPrecio.setText("jLabel3");

        jLabel3.setText("Estado");

        lblDigEstado.setText("jLabel3");

        jLabel16.setText("Años");

        lblDigAnos.setText("jLabel3");

        javax.swing.GroupLayout dialogoEliminarLayout = new javax.swing.GroupLayout(dialogoEliminar.getContentPane());
        dialogoEliminar.getContentPane().setLayout(dialogoEliminarLayout);
        dialogoEliminarLayout.setHorizontalGroup(
            dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialogoEliminarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDigMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDigPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigAnos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addComponent(btnDigAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDigCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        dialogoEliminarLayout.setVerticalGroup(
            dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoEliminarLayout.createSequentialGroup()
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigMatricula))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigMarca))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigModelo)))
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigEstado))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigAnos))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigPrecio))))
                .addGap(18, 18, 18)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigAceptar)
                    .addComponent(btnDigCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogoModificar.setTitle("MODIFICAR");
        dialogoModificar.setMinimumSize(new java.awt.Dimension(416, 299));
        dialogoModificar.setModal(true);
        dialogoModificar.setResizable(false);
        dialogoModificar.setSize(new java.awt.Dimension(472, 385));

        jLabel6.setText("MODIFICACIONES");

        lblModMatricula.setText("Matricula");

        lblModModelo.setText("Modelo");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/resume(1).png"))); // NOI18N

        btnModAceptar.setText("Aceptar");
        btnModAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAceptarActionPerformed(evt);
            }
        });

        btnDigCancelar1.setText("Cancelar");
        btnDigCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigCancelar1ActionPerformed(evt);
            }
        });

        lblModFecha.setText("Fecha PM");

        lblModPrecio.setText("Precio día");

        entModMatricula.setEditable(false);

        lblModMarca.setText("Marca");

        lblModFechaNac.setText("Estado");

        javax.swing.GroupLayout dialogoModificarLayout = new javax.swing.GroupLayout(dialogoModificar.getContentPane());
        dialogoModificar.getContentPane().setLayout(dialogoModificarLayout);
        dialogoModificarLayout.setHorizontalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addComponent(lblModMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entModMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addComponent(lblModModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entModModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addComponent(lblModMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entModMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblModPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entModPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entModFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entModEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDigCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        dialogoModificarLayout.setVerticalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModAceptar)
                    .addComponent(btnDigCancelar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogoDatos.setTitle("DATOS");
        dialogoDatos.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoDatos.setModal(true);
        dialogoDatos.setResizable(false);
        dialogoDatos.setSize(new java.awt.Dimension(416, 339));

        jLabel7.setText("DATOS DEL COCHE");

        lblMatriculaData.setText("Matricula");

        lblDataMatricula.setText("jLabel3");

        lblEstadoData.setText("Estado");

        lblDataEstado.setText("jLabel3");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contact-form.png"))); // NOI18N

        btnDatosAceptar.setText("Aceptar");
        btnDatosAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAceptarActionPerformed(evt);
            }
        });

        lblModeloData.setText("Modelo");

        lblDataModelo.setText("jLabel3");

        lblPrecioData.setText("Precio día");

        lblDataPrecio.setText("jLabel3");

        lblFechaData.setText("Fecha PM");

        lblDataFecha.setText("jLabel3");

        lblAnhosData.setText("Años");

        lblDataAnhos.setText("jLabel3");

        lblmarcaData.setText("Marca");

        lblDataMarca.setText("jLabel3");

        javax.swing.GroupLayout dialogoDatosLayout = new javax.swing.GroupLayout(dialogoDatos.getContentPane());
        dialogoDatos.getContentPane().setLayout(dialogoDatosLayout);
        dialogoDatosLayout.setHorizontalGroup(
            dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoDatosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogoDatosLayout.createSequentialGroup()
                                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMatriculaData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModeloData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDataModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dialogoDatosLayout.createSequentialGroup()
                                .addComponent(lblmarcaData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoDatosLayout.createSequentialGroup()
                                .addComponent(lblEstadoData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAnhosData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataAnhos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel18)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnDatosAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoDatosLayout.setVerticalGroup(
            dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoDatosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMatriculaData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataMatricula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblModeloData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataModelo)))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataFecha))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnhosData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataAnhos)
                            .addComponent(lblmarcaData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataMarca))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataPrecio))))
                .addGap(0, 0, 0)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataEstado))
                .addGap(18, 18, 18)
                .addComponent(btnDatosAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        setBorder(new javax.swing.border.MatteBorder(null));

        boxCliente.setBorder(new javax.swing.border.MatteBorder(null));

        lblMatriculaCoc.setText("Matricula");

        lblMarcaCoc.setText("Marca");

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/sedan-car-front.png"))); // NOI18N

        btnDatos.setText("Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblMatricula.setText("lblNombre");

        btnModCoc.setText("Modificar");
        btnModCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCocActionPerformed(evt);
            }
        });

        lblMarca.setText("lblMarca");

        lblModelo.setText("lblModelo");

        lblModeloCoc.setText("Modelo");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxClienteLayout = new javax.swing.GroupLayout(boxCliente);
        boxCliente.setLayout(boxClienteLayout);
        boxClienteLayout.setHorizontalGroup(
            boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxClienteLayout.createSequentialGroup()
                        .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(boxClienteLayout.createSequentialGroup()
                                .addComponent(lblMatriculaCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))
                            .addGroup(boxClienteLayout.createSequentialGroup()
                                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(boxClienteLayout.createSequentialGroup()
                                        .addComponent(lblModeloCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(boxClienteLayout.createSequentialGroup()
                                        .addComponent(lblMarcaCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(34, 34, 34))))))
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(lblImg)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        boxClienteLayout.setVerticalGroup(
            boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatriculaCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMarcaCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblModeloCoc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnModCoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDigAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigAceptarActionPerformed
        Session sesion = NewHibernateUtil.getSession();
        sesion.beginTransaction();
        sesion.delete(cocheRepresentado);
        sesion.getTransaction().commit();
        sesion.close();
        panelPadre.listarCoches();
        dialogoEliminar.setVisible(false);
    }//GEN-LAST:event_btnDigAceptarActionPerformed

    private void btnDigCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigCancelarActionPerformed
        dialogoEliminar.setVisible(false);
    }//GEN-LAST:event_btnDigCancelarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        this.lblDataMatricula.setText(cocheRepresentado.getMatricula());
        this.lblDataMarca.setText(cocheRepresentado.getMarca());
        this.lblDataModelo.setText(cocheRepresentado.getModelo());
        this.lblDataEstado.setText(cocheRepresentado.getEstado());
        this.lblDataPrecio.setText(String.valueOf(cocheRepresentado.getPrecioDia()));
        this.lblDataAnhos.setText(String.valueOf(cocheRepresentado.getAnhos()));
        this.lblDataFecha.setText(sdf.format(cocheRepresentado.getFechaM()));
        dialogoDatos.setVisible(true);
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Session sesion = NewHibernateUtil.getSession();
        sesion.beginTransaction();
        this.lblDigMatricula.setText(cocheRepresentado.getMatricula());
        this.lblDigEstado.setText(cocheRepresentado.getEstado());
        this.lblDigAnos.setText(String.valueOf(cocheRepresentado.getAnhos()));
        this.lblDigModelo.setText(cocheRepresentado.getModelo());
        this.lblDigPrecio.setText(String.valueOf(cocheRepresentado.getPrecioDia()));
        this.lblDigMarca.setText(cocheRepresentado.getMarca());
        sesion.close();
        dialogoEliminar.setVisible(true);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCocActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        this.entModMatricula.setText(cocheRepresentado.getMatricula());
        this.entModMarca.setText(cocheRepresentado.getMarca());
        this.entModModelo.setText(cocheRepresentado.getModelo());
        this.entModEstado.setText(cocheRepresentado.getEstado());
        this.entModPrecio.setText(String.valueOf(cocheRepresentado.getPrecioDia()));
        Date fechaPM= cocheRepresentado.getFechaM();
        String fechaString = sdf.format(fechaPM);
        this.entModFecha.setText(fechaString);
        dialogoModificar.setVisible(true);
    }//GEN-LAST:event_btnModCocActionPerformed

    private void btnModAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAceptarActionPerformed
        try{
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
            Date fechaPM = sdf.parse(entModFecha.getText());
            Date fechaHoy = new Date();
            int d1 = Integer.parseInt(formatter.format(fechaPM));
            int d2 = Integer.parseInt(formatter.format(fechaHoy));
            int anhos = (d2-d1)/10000;
            entModMatricula.setText(cocheRepresentado.getMatricula());
            cocheRepresentado.setMarca(entModMarca.getText());
            cocheRepresentado.setModelo(entModModelo.getText());
            cocheRepresentado.setAnhos(anhos);
            cocheRepresentado.setFechaM(fechaPM);
            cocheRepresentado.setPrecioDia(Float.parseFloat(entModPrecio.getText()));
            cocheRepresentado.setEstado(entModEstado.getText());
            Modificar.coches(cocheRepresentado);
        }catch(ParseException pe){
            System.out.println(pe);
        }
        panelPadre.listarCoches();
        this.dialogoModificar.setVisible(false);
    }//GEN-LAST:event_btnModAceptarActionPerformed

    private void btnDigCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigCancelar1ActionPerformed
        dialogoModificar.setVisible(false);
    }//GEN-LAST:event_btnDigCancelar1ActionPerformed

    private void btnDatosAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAceptarActionPerformed
        dialogoDatos.setVisible(false);
    }//GEN-LAST:event_btnDatosAceptarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        ((Alquileres)panelPadre).setCocheSel(cocheRepresentado);
        ((Alquileres)panelPadre).getSeleccionCoche().setVisible(false);
        ((Alquileres)panelPadre).getEntCoche().setText(cocheRepresentado.getMatricula());
        ((Alquileres)panelPadre).getEntCoche().setEnabled(false);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    public ICochesAlquileres getPanelPadre() {
        return panelPadre;
    }

    public void setPanelPadre(ICochesAlquileres panelPadre) {
        this.panelPadre = panelPadre;
    }

    public Coche getCocheRepresentado() {
        return cocheRepresentado;
    }

    public void setCocheRepresentado(Coche cocheRepresentado) {
        this.cocheRepresentado = cocheRepresentado;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnModCoc() {
        return btnModCoc;
    }

    public void setBtnModCoc(JButton btnModCoc) {
        this.btnModCoc = btnModCoc;
    }

    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public void setBtnSeleccionar(JButton btnSeleccionar) {
        this.btnSeleccionar = btnSeleccionar;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCliente;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnDatosAceptar;
    private javax.swing.JButton btnDigAceptar;
    private javax.swing.JButton btnDigCancelar;
    private javax.swing.JButton btnDigCancelar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModAceptar;
    private javax.swing.JButton btnModCoc;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JDialog dialogoDatos;
    private javax.swing.JDialog dialogoEliminar;
    private javax.swing.JDialog dialogoModificar;
    private javax.swing.JTextField entModEstado;
    private javax.swing.JTextField entModFecha;
    private javax.swing.JTextField entModMarca;
    private javax.swing.JTextField entModMatricula;
    private javax.swing.JTextField entModModelo;
    private javax.swing.JTextField entModPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblAnhosData;
    private javax.swing.JLabel lblDataAnhos;
    private javax.swing.JLabel lblDataEstado;
    private javax.swing.JLabel lblDataFecha;
    private javax.swing.JLabel lblDataMarca;
    private javax.swing.JLabel lblDataMatricula;
    private javax.swing.JLabel lblDataModelo;
    private javax.swing.JLabel lblDataPrecio;
    private javax.swing.JLabel lblDigAnos;
    private javax.swing.JLabel lblDigEstado;
    private javax.swing.JLabel lblDigMarca;
    private javax.swing.JLabel lblDigMatricula;
    private javax.swing.JLabel lblDigModelo;
    private javax.swing.JLabel lblDigPrecio;
    private javax.swing.JLabel lblEstadoData;
    private javax.swing.JLabel lblFechaData;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMarcaCoc;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblMatriculaCoc;
    private javax.swing.JLabel lblMatriculaData;
    private javax.swing.JLabel lblModFecha;
    private javax.swing.JLabel lblModFechaNac;
    private javax.swing.JLabel lblModMarca;
    private javax.swing.JLabel lblModMatricula;
    private javax.swing.JLabel lblModModelo;
    private javax.swing.JLabel lblModPrecio;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblModeloCoc;
    private javax.swing.JLabel lblModeloData;
    private javax.swing.JLabel lblPrecioData;
    private javax.swing.JLabel lblmarcaData;
    // End of variables declaration//GEN-END:variables
}
