package paneles;

import hibernate.NewHibernateUtil;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import metodos.Buscar;
import metodos.Modificar;
import org.hibernate.Session;
import pojos.Alquiler;
import pojos.Cliente;
import pojos.Empresa;
import pojos.Particular;

public class boxClientes extends javax.swing.JPanel {

    /**
     * Creates new form boxClientes
     */
    private JPanel panelMain;
    private JPanel panelMainEmpresas;
    private IClientesAlquileres panelPadre;
    private Cliente clienteRepresentado;
    private JFrame aplicacion;
    private JDialog CentrarEnDialogo;
    
    public boxClientes(String nombre, String dni) {
        initComponents();
        lblNombre.setText(nombre);
        lblDni.setText(dni);
        btnSeleccionar.setVisible(false);
        panelAlquiler.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoEliminar = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        lblNombreEliminar = new javax.swing.JLabel();
        lblDigNombre = new javax.swing.JLabel();
        lblTelfEliminar = new javax.swing.JLabel();
        lblDigTelf = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnDigAceptar = new javax.swing.JButton();
        btnDigCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblEdadEliminar = new javax.swing.JLabel();
        lblDigEdad = new javax.swing.JLabel();
        lblPuntosEliminar = new javax.swing.JLabel();
        lblDigPuntos = new javax.swing.JLabel();
        lblDniEliminar = new javax.swing.JLabel();
        lblDigDni = new javax.swing.JLabel();
        lblEmailEliminar = new javax.swing.JLabel();
        lblDigEmail = new javax.swing.JLabel();
        dialogoModificar = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        lblModNombre = new javax.swing.JLabel();
        lblModApel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnModAceptar = new javax.swing.JButton();
        btnDigCancelar1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblModDni = new javax.swing.JLabel();
        lblModEmail = new javax.swing.JLabel();
        entModNombre = new javax.swing.JTextField();
        entModDni = new javax.swing.JTextField();
        entModApel = new javax.swing.JTextField();
        entModEmail = new javax.swing.JTextField();
        entModTelf = new javax.swing.JTextField();
        entModFechNac = new javax.swing.JTextField();
        lblModTelefono = new javax.swing.JLabel();
        lblModFechaNac = new javax.swing.JLabel();
        entModPuntos = new javax.swing.JTextField();
        lblModPuntos = new javax.swing.JLabel();
        dialogoDatos = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        lblNombreData = new javax.swing.JLabel();
        lblDataNombre = new javax.swing.JLabel();
        lblTelfData = new javax.swing.JLabel();
        lblDataTelf = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnDatosAceptar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lblEdadData = new javax.swing.JLabel();
        lblDataEdad = new javax.swing.JLabel();
        lblPuntosData = new javax.swing.JLabel();
        lblDataPuntos = new javax.swing.JLabel();
        lblDniData = new javax.swing.JLabel();
        lblDataDni = new javax.swing.JLabel();
        lblEmailData = new javax.swing.JLabel();
        lblDataEmail = new javax.swing.JLabel();
        lblFechaData = new javax.swing.JLabel();
        lblDataFecha = new javax.swing.JLabel();
        lblApelData = new javax.swing.JLabel();
        lblDataApel = new javax.swing.JLabel();
        panelAlquiler = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        panelAlquilerBox = new javax.swing.JPanel();
        btnHideAlquiler = new javax.swing.JButton();
        btnVerAlquilerParticular = new javax.swing.JButton();
        dialogoDatosEmpresa = new javax.swing.JDialog();
        jLabel8 = new javax.swing.JLabel();
        lblNombreData1 = new javax.swing.JLabel();
        lblDataNombreEmpresa = new javax.swing.JLabel();
        lblTelfData1 = new javax.swing.JLabel();
        lblDataTelfEmpresa = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnDatosEmpresaAceptar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        lblDniData1 = new javax.swing.JLabel();
        lblDataCif = new javax.swing.JLabel();
        lblEmailData1 = new javax.swing.JLabel();
        lblDataEmailEmpresa = new javax.swing.JLabel();
        panelAlquileres = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        panelAlquileresBox = new javax.swing.JPanel();
        btnHideAlquileres = new javax.swing.JButton();
        btnVerAlquileresEmpresas = new javax.swing.JButton();
        boxCliente = new javax.swing.JPanel();
        lblNomCli = new javax.swing.JLabel();
        lblDniCli = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();
        btnDatos = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        btnModCli = new javax.swing.JButton();
        lblDni = new javax.swing.JLabel();
        btnSeleccionar = new javax.swing.JButton();

        dialogoEliminar.setTitle("ALERTA");
        dialogoEliminar.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoEliminar.setModal(true);
        dialogoEliminar.setResizable(false);
        dialogoEliminar.setSize(new java.awt.Dimension(416, 289));

        jLabel1.setText("DESEA ELIMINAR AL CLIENTE?");

        lblNombreEliminar.setText("Nombre");

        lblDigNombre.setText("jLabel3");

        lblTelfEliminar.setText("Telefono");

        lblDigTelf.setText("jLabel3");

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/exclamation-mark.png"))); // NOI18N

        btnDigAceptar.setText("Aceptar");
        btnDigAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigAceptarActionPerformed(evt);
            }
        });

        btnDigCancelar.setText("Cancelar");
        btnDigCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigCancelarActionPerformed(evt);
            }
        });

        lblEdadEliminar.setText("Edad");

        lblDigEdad.setText("jLabel3");

        lblPuntosEliminar.setText("Puntos");

        lblDigPuntos.setText("jLabel3");

        lblDniEliminar.setText("Dni/Cif");

        lblDigDni.setText("jLabel3");

        lblEmailEliminar.setText("Email");

        lblDigEmail.setText("jLabel3");

        javax.swing.GroupLayout dialogoEliminarLayout = new javax.swing.GroupLayout(dialogoEliminar.getContentPane());
        dialogoEliminar.getContentPane().setLayout(dialogoEliminarLayout);
        dialogoEliminarLayout.setHorizontalGroup(
            dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dialogoEliminarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTelfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdadEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDigTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPuntosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDniEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDigPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigDni, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDigEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addComponent(btnDigAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDigCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        dialogoEliminarLayout.setVerticalGroup(
            dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoEliminarLayout.createSequentialGroup()
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoEliminarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigNombre))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelfEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigTelf))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigEdad)))
                    .addGroup(dialogoEliminarLayout.createSequentialGroup()
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDniEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigDni))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigEmail))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDigPuntos))))
                .addGap(18, 18, 18)
                .addGroup(dialogoEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDigAceptar)
                    .addComponent(btnDigCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogoModificar.setTitle("ALERTA");
        dialogoModificar.setMinimumSize(new java.awt.Dimension(416, 299));
        dialogoModificar.setModal(true);
        dialogoModificar.setResizable(false);
        dialogoModificar.setSize(new java.awt.Dimension(472, 385));

        jLabel6.setText("MODIFICACIONES");

        lblModNombre.setText("Nombre");

        lblModApel.setText("Apellidos");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/resume(1).png"))); // NOI18N

        btnModAceptar.setText("Aceptar");
        btnModAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModAceptarActionPerformed(evt);
            }
        });

        btnDigCancelar1.setText("Cancelar");
        btnDigCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDigCancelar1ActionPerformed(evt);
            }
        });

        lblModDni.setText("Dni/Cif");

        lblModEmail.setText("Email");

        lblModTelefono.setText("Telefono");

        lblModFechaNac.setText("Fecha Nac");

        lblModPuntos.setText("Puntos");

        javax.swing.GroupLayout dialogoModificarLayout = new javax.swing.GroupLayout(dialogoModificar.getContentPane());
        dialogoModificar.getContentPane().setLayout(dialogoModificarLayout);
        dialogoModificarLayout.setHorizontalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entModPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addComponent(lblModApel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entModApel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addComponent(lblModTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(entModTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoModificarLayout.createSequentialGroup()
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblModEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModFechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblModDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(entModEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entModDni, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(entModFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnDigCancelar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        dialogoModificarLayout.setVerticalGroup(
            dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoModificarLayout.createSequentialGroup()
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModDni, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModTelf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModApel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModApel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblModFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(entModFechNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(entModPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(dialogoModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModAceptar)
                    .addComponent(btnDigCancelar1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dialogoDatos.setTitle("ALERTA");
        dialogoDatos.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoDatos.setModal(true);
        dialogoDatos.setResizable(false);
        dialogoDatos.setSize(new java.awt.Dimension(416, 339));

        jLabel7.setText("DATOS DEL CLIENTE");

        lblNombreData.setText("Nombre");

        lblDataNombre.setText("jLabel3");

        lblTelfData.setText("Telefono");

        lblDataTelf.setText("jLabel3");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contact-form.png"))); // NOI18N

        btnDatosAceptar.setText("Aceptar");
        btnDatosAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosAceptarActionPerformed(evt);
            }
        });

        lblEdadData.setText("Edad");

        lblDataEdad.setText("jLabel3");

        lblPuntosData.setText("Puntos");

        lblDataPuntos.setText("jLabel3");

        lblDniData.setText("Dni/Cif");

        lblDataDni.setText("jLabel3");

        lblEmailData.setText("Email");

        lblDataEmail.setText("jLabel3");

        lblFechaData.setText("FechaNac");

        lblDataFecha.setText("jLabel3");

        lblApelData.setText("Apellidos");

        lblDataApel.setText("jLabel3");

        panelAlquiler.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setText("ALQUILER");

        panelAlquilerBox.setLayout(new java.awt.BorderLayout());

        btnHideAlquiler.setText("<<<");
        btnHideAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideAlquilerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlquilerLayout = new javax.swing.GroupLayout(panelAlquiler);
        panelAlquiler.setLayout(panelAlquilerLayout);
        panelAlquilerLayout.setHorizontalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlquilerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHideAlquiler)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(134, 134, 134))
            .addComponent(jSeparator5)
            .addComponent(panelAlquilerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAlquilerLayout.setVerticalGroup(
            panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquilerLayout.createSequentialGroup()
                .addGroup(panelAlquilerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAlquilerLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlquilerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnHideAlquiler)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelAlquilerBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerAlquilerParticular.setText("Ver Alquileres >>>");
        btnVerAlquilerParticular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlquilerParticularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoDatosLayout = new javax.swing.GroupLayout(dialogoDatos.getContentPane());
        dialogoDatos.getContentPane().setLayout(dialogoDatosLayout);
        dialogoDatosLayout.setHorizontalGroup(
            dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator3)
                        .addGroup(dialogoDatosLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(dialogoDatosLayout.createSequentialGroup()
                                    .addComponent(btnDatosAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnVerAlquilerParticular, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(dialogoDatosLayout.createSequentialGroup()
                                    .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(dialogoDatosLayout.createSequentialGroup()
                                            .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblEdadData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDataNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDataEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(dialogoDatosLayout.createSequentialGroup()
                                            .addComponent(lblApelData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblDataApel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(dialogoDatosLayout.createSequentialGroup()
                                            .addComponent(lblTelfData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblDataTelf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dialogoDatosLayout.createSequentialGroup()
                                            .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPuntosData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDniData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblEmailData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDataPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDataDni, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblDataEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(dialogoDatosLayout.createSequentialGroup()
                                            .addComponent(lblFechaData, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblDataFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel18)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)))
                .addGap(0, 0, 0)
                .addComponent(panelAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoDatosLayout.setVerticalGroup(
            dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoDatosLayout.createSequentialGroup()
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoDatosLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataEdad)))
                    .addGroup(dialogoDatosLayout.createSequentialGroup()
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDniData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataDni))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmailData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataEmail)
                            .addComponent(lblApelData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataApel))
                        .addGap(0, 0, 0)
                        .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPuntosData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataPuntos))))
                .addGap(0, 0, 0)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelfData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataTelf))
                    .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblFechaData, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataFecha)))
                .addGap(18, 18, 18)
                .addGroup(dialogoDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatosAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerAlquilerParticular))
                .addContainerGap())
            .addComponent(panelAlquiler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        dialogoDatosEmpresa.setTitle("ALERTA");
        dialogoDatosEmpresa.setMinimumSize(new java.awt.Dimension(416, 289));
        dialogoDatosEmpresa.setModal(true);
        dialogoDatosEmpresa.setResizable(false);
        dialogoDatosEmpresa.setSize(new java.awt.Dimension(413, 333));

        jLabel8.setText("DATOS DE LA EMPRESA");

        lblNombreData1.setText("Nombre");

        lblDataNombreEmpresa.setText("jLabel3");

        lblTelfData1.setText("Telefono");

        lblDataTelfEmpresa.setText("jLabel3");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/contact-form.png"))); // NOI18N

        btnDatosEmpresaAceptar.setText("Aceptar");
        btnDatosEmpresaAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosEmpresaAceptarActionPerformed(evt);
            }
        });

        lblDniData1.setText("Dni/Cif");

        lblDataCif.setText("jLabel3");

        lblEmailData1.setText("Email");

        lblDataEmailEmpresa.setText("jLabel3");

        panelAlquileres.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setText("ALQUILERES");

        panelAlquileresBox.setLayout(new java.awt.BorderLayout());

        btnHideAlquileres.setText("<<<");
        btnHideAlquileres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHideAlquileresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAlquileresLayout = new javax.swing.GroupLayout(panelAlquileres);
        panelAlquileres.setLayout(panelAlquileresLayout);
        panelAlquileresLayout.setHorizontalGroup(
            panelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAlquileresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnHideAlquileres)
                .addGap(50, 50, 50)
                .addComponent(jLabel3)
                .addContainerGap(158, Short.MAX_VALUE))
            .addComponent(jSeparator6)
            .addComponent(panelAlquileresBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAlquileresLayout.setVerticalGroup(
            panelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAlquileresLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(panelAlquileresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHideAlquileres)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAlquileresBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerAlquileresEmpresas.setText("Ver Alquileres >>>");
        btnVerAlquileresEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerAlquileresEmpresasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dialogoDatosEmpresaLayout = new javax.swing.GroupLayout(dialogoDatosEmpresa.getContentPane());
        dialogoDatosEmpresa.getContentPane().setLayout(dialogoDatosEmpresaLayout);
        dialogoDatosEmpresaLayout.setHorizontalGroup(
            dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                        .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel19)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel8))
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoDatosEmpresaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                                .addComponent(lblNombreData1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataNombreEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                                .addComponent(lblTelfData1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDataTelfEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDniData1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmailData1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataCif, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDataEmailEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnDatosEmpresaAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerAlquileresEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(panelAlquileres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogoDatosEmpresaLayout.setVerticalGroup(
            dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosEmpresaLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dialogoDatosEmpresaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)))
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombreData1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataNombreEmpresa))
                    .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDniData1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDataCif)))
                .addGap(18, 18, 18)
                .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailData1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataEmailEmpresa)
                    .addComponent(lblTelfData1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataTelfEmpresa))
                .addGap(18, 18, 18)
                .addGroup(dialogoDatosEmpresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatosEmpresaAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerAlquileresEmpresas))
                .addContainerGap(52, Short.MAX_VALUE))
            .addComponent(panelAlquileres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBorder(new javax.swing.border.MatteBorder(null));

        boxCliente.setBorder(new javax.swing.border.MatteBorder(null));

        lblNomCli.setText("Nombre");

        lblDniCli.setText("DNI/CIF");

        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/man-user(1).png"))); // NOI18N

        btnDatos.setText("Datos");
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblNombre.setText("lblNombre");

        btnModCli.setText("Modificar");
        btnModCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModCliActionPerformed(evt);
            }
        });

        lblDni.setText("lblDni");

        btnSeleccionar.setText("Seleccionar");
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout boxClienteLayout = new javax.swing.GroupLayout(boxCliente);
        boxCliente.setLayout(boxClienteLayout);
        boxClienteLayout.setHorizontalGroup(
            boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(boxClienteLayout.createSequentialGroup()
                        .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeleccionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModCli, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblNomCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boxClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblImg)
                .addGap(97, 97, 97))
        );
        boxClienteLayout.setVerticalGroup(
            boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boxClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomCli, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDniCli, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModCli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(boxClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSeleccionar)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(boxCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        if(clienteRepresentado instanceof Particular){
            this.lblDataDni.setText(((Particular)clienteRepresentado).getDni());
            this.lblDataEmail.setText(((Particular)clienteRepresentado).getEmail());
            this.lblDataNombre.setText(((Particular)clienteRepresentado).getNombre());
            this.lblDataTelf.setText(((Particular)clienteRepresentado).getTelefono());
            this.lblDataApel.setText(((Particular)clienteRepresentado).getApellidos());
            String edad = String.valueOf(((Particular)clienteRepresentado).getEdad());
            this.lblDataEdad.setText(edad);
            Date fechaNacNoMod = ((Particular)clienteRepresentado).getFechaNacimiento();
            String fechaString = sdf.format(fechaNacNoMod);
            this.lblDataFecha.setText(fechaString);
            int puntos = ((Particular)clienteRepresentado).getPuntos();
            this.lblDataPuntos.setText(String.valueOf(puntos));
            dialogoDatos.setVisible(true);
        }else{
            this.lblDataCif.setText(((Empresa)clienteRepresentado).getCif());
            this.lblDataEmailEmpresa.setText(((Empresa)clienteRepresentado).getEmail());
            this.lblDataTelfEmpresa.setText(((Empresa)clienteRepresentado).getTelefono());
            this.lblDataNombreEmpresa.setText(((Empresa)clienteRepresentado).getNombre());
            this.lblDataNombreEmpresa.setToolTipText(((Empresa)clienteRepresentado).getNombre());
            dialogoDatosEmpresa.setVisible(true);
        }  
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(clienteRepresentado instanceof Particular){
            lblPuntosEliminar.setVisible(true);
            lblEdadEliminar.setVisible(true);
            lblDigEdad.setVisible(true);
            lblDigPuntos.setVisible(true);
            this.lblDigNombre.setText(((Particular)clienteRepresentado).getNombre());
            this.lblDigDni.setText(((Particular)clienteRepresentado).getDni());
            this.lblDigEmail.setText(clienteRepresentado.getEmail());
            this.lblDigEdad.setText(String.valueOf(((Particular)clienteRepresentado).getEdad()));
            this.lblDigPuntos.setText(String.valueOf(((Particular)clienteRepresentado).getPuntos()));
            this.lblDigTelf.setText(clienteRepresentado.getTelefono());
            dialogoEliminar.setVisible(true);
        }else{
            lblPuntosEliminar.setVisible(false);
            lblEdadEliminar.setVisible(false);
            lblDigEdad.setVisible(false);
            lblDigPuntos.setVisible(false);
            this.lblDigNombre.setText(((Empresa)clienteRepresentado).getNombre());
            this.lblDigDni.setText(((Empresa)clienteRepresentado).getCif());
            this.lblDigEmail.setText(clienteRepresentado.getEmail());
            this.lblDigTelf.setText(clienteRepresentado.getTelefono());
            dialogoEliminar.setVisible(true);
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDigAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigAceptarActionPerformed
        Session sesion = NewHibernateUtil.getSession();
        sesion.beginTransaction();
        sesion.delete(clienteRepresentado);
        sesion.getTransaction().commit();
        sesion.close();
        panelPadre.listarClientes();
        dialogoEliminar.setVisible(false);
    }//GEN-LAST:event_btnDigAceptarActionPerformed

    private void btnDigCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigCancelarActionPerformed
        dialogoEliminar.setVisible(false);
    }//GEN-LAST:event_btnDigCancelarActionPerformed

    private void btnModCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModCliActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
        if(clienteRepresentado instanceof Particular){
            this.lblModApel.setVisible(true);
            this.entModApel.setVisible(true);
            this.lblModFechaNac.setVisible(true);
            this.entModFechNac.setVisible(true);
            this.lblModPuntos.setVisible(true);
            this.entModPuntos.setVisible(true);
            this.entModDni.setText(((Particular)clienteRepresentado).getDni());
            this.entModEmail.setText(((Particular)clienteRepresentado).getEmail());
            this.entModNombre.setText(((Particular)clienteRepresentado).getNombre());
            this.entModTelf.setText(((Particular)clienteRepresentado).getTelefono());
            this.entModApel.setText(((Particular)clienteRepresentado).getApellidos());
            Date fechaNacNoMod = ((Particular)clienteRepresentado).getFechaNacimiento();
            String fechaString = sdf.format(fechaNacNoMod);
            this.entModFechNac.setText(fechaString);
            int puntos = ((Particular)clienteRepresentado).getPuntos();
            this.entModPuntos.setText(String.valueOf(puntos));
        }else{
            this.lblModApel.setVisible(false);
            this.entModApel.setVisible(false);
            this.lblModFechaNac.setVisible(false);
            this.entModFechNac.setVisible(false);
            this.lblModPuntos.setVisible(false);
            this.entModPuntos.setVisible(false);
            this.entModDni.setText(((Empresa)clienteRepresentado).getCif());
            this.entModEmail.setText(((Empresa)clienteRepresentado).getEmail());
            this.entModTelf.setText(((Empresa)clienteRepresentado).getTelefono());
            this.entModNombre.setText(((Empresa)clienteRepresentado).getNombre());
        }
        dialogoModificar.setVisible(true);
    }//GEN-LAST:event_btnModCliActionPerformed

    private void btnModAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModAceptarActionPerformed
        try{
            if(clienteRepresentado instanceof Particular){
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
                DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
                Date fechaNac = sdf.parse(this.entModFechNac.getText());
                int puntosMod = Integer.parseInt(this.entModPuntos.getText());
                Date fechaHoy = new Date();
                int d1 = Integer.parseInt(formatter.format(fechaNac));
                int d2 = Integer.parseInt(formatter.format(fechaHoy));
                int edad = (d2-d1)/10000;
                ((Particular)clienteRepresentado).setDni(this.entModDni.getText());
                ((Particular)clienteRepresentado).setFechaNacimiento(fechaNac);
                ((Particular)clienteRepresentado).setEdad(edad);
                ((Particular)clienteRepresentado).setNombre(this.entModNombre.getText());
                ((Particular)clienteRepresentado).setEmail(this.entModEmail.getText());
                ((Particular)clienteRepresentado).setTelefono(this.entModTelf.getText());
                ((Particular)clienteRepresentado).setPuntos(puntosMod);
                Modificar.particulares(((Particular)clienteRepresentado));               
                panelPadre.listarClientes();
            }else {
                ((Empresa)clienteRepresentado).setCif(this.entModDni.getText());
                ((Empresa)clienteRepresentado).setNombre(this.entModNombre.getText());
                ((Empresa)clienteRepresentado).setEmail(this.entModEmail.getText());
                ((Empresa)clienteRepresentado).setTelefono(this.entModTelf.getText());
                Modificar.empresas(((Empresa)clienteRepresentado));
                panelPadre.listarClientes();
            }
        }catch(ParseException pe){
            System.out.println(pe);
        }
        panelPadre.listarClientes();
        this.dialogoModificar.setVisible(false);
    }//GEN-LAST:event_btnModAceptarActionPerformed

    private void btnDigCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigCancelar1ActionPerformed
        dialogoModificar.setVisible(false);
    }//GEN-LAST:event_btnDigCancelar1ActionPerformed

    private void btnDatosAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosAceptarActionPerformed
        panelAlquiler.setVisible(false);
        dialogoDatos.setSize(416, 339);
        dialogoDatos.setVisible(false);
    }//GEN-LAST:event_btnDatosAceptarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        ((Alquileres)panelPadre).setClienteSel(clienteRepresentado);
        ((Alquileres)panelPadre).getSeleccionCliente().setVisible(false);
        if(clienteRepresentado instanceof Particular) {
            ((Alquileres)panelPadre).getEntCliente().setText(((Particular)clienteRepresentado).getDni());
        }else {
            ((Alquileres)panelPadre).getEntCliente().setText(((Empresa)clienteRepresentado).getCif());
        }
        ((Alquileres)panelPadre).getEntCliente().setEnabled(false);
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnDatosEmpresaAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosEmpresaAceptarActionPerformed
        panelAlquileres.setVisible(false);
        dialogoDatosEmpresa.setSize(413, 333);
        dialogoDatosEmpresa.setVisible(false);
    }//GEN-LAST:event_btnDatosEmpresaAceptarActionPerformed

    private void btnVerAlquilerParticularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlquilerParticularActionPerformed
        if(panelMain != null){
            panelMain.removeAll();
            panelMain.revalidate();
            panelMain.repaint();
            panelAlquilerBox.remove(panelMain);
            panelAlquilerBox.revalidate();
            panelAlquilerBox.repaint();
        }
        panelMain = new JPanel();
        GridBagLayout innerLayout = new GridBagLayout();
        panelMain.setLayout(innerLayout);
        panelAlquilerBox.add(panelMain);
        panelAlquiler.setVisible(true);
        dialogoDatos.setSize(747, 350);
        List<Alquiler> alquileres = Buscar.alquileres("", "", "", null, ((Particular)clienteRepresentado), null);
        if(!alquileres.isEmpty()){
            Alquiler alquiler = alquileres.get(0);
            boxAlquileres boxAlquileres = new boxAlquileres(((Particular)clienteRepresentado).getDni(), alquiler.getCoche().getMatricula(), alquiler.getCodigo());
            boxAlquileres.setAlquilerRepresentado(alquiler);
            panelMain.add(boxAlquileres);
        }
    }//GEN-LAST:event_btnVerAlquilerParticularActionPerformed

    private void btnHideAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideAlquilerActionPerformed
        panelAlquiler.setVisible(false);
        dialogoDatos.setSize(416, 339);
    }//GEN-LAST:event_btnHideAlquilerActionPerformed

    private void btnHideAlquileresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHideAlquileresActionPerformed
        panelAlquileres.setVisible(false);
        dialogoDatosEmpresa.setSize(413, 333);
    }//GEN-LAST:event_btnHideAlquileresActionPerformed

    private void btnVerAlquileresEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerAlquileresEmpresasActionPerformed
        if(panelMainEmpresas != null){
            panelMainEmpresas.removeAll();
            panelMainEmpresas.revalidate();
            panelMainEmpresas.repaint();
            panelAlquileresBox.remove(panelMainEmpresas);
            panelAlquileresBox.revalidate();
            panelAlquileresBox.repaint();
        }
        panelMainEmpresas = new JPanel();
        GridBagLayout innerLayout = new GridBagLayout();
        panelMainEmpresas.setLayout(innerLayout);
        //panelAlquileresBox.add(panelMainEmpresas);
        panelAlquileres.setVisible(true);
        dialogoDatosEmpresa.setSize(700, 375);
        List<Alquiler> alquileres = Buscar.alquileres("", "", "", null, null, ((Empresa)clienteRepresentado));
        if(!alquileres.isEmpty()){
            int i = 0;
            for(Alquiler alquiler : alquileres){
                boxAlquileres boxAlquileres = new boxAlquileres(((Empresa)clienteRepresentado).getCif(), alquiler.getCoche().getMatricula(), alquiler.getCodigo());
                boxAlquileres.setAlquilerRepresentado(alquiler);
                panelMainEmpresas.add(boxAlquileres);
                i++;
            }
        }
        
        JScrollPane scrollPanel = new JScrollPane(panelMainEmpresas);
        scrollPanel.getVerticalScrollBar().setUnitIncrement(16);
        panelAlquileresBox.add(scrollPanel, BorderLayout.CENTER);
    }//GEN-LAST:event_btnVerAlquileresEmpresasActionPerformed

    public IClientesAlquileres getPanelPadre() {
        return panelPadre;
    }

    public void setPanelPadre(IClientesAlquileres panelPadre) {
        this.panelPadre = panelPadre;
    }

    public Cliente getClienteRepresentado() {
        return clienteRepresentado;
    }

    public void setClienteRepresentado(Cliente clienteRepresentado) {
        this.clienteRepresentado = clienteRepresentado;
    }

    public JFrame getAplicacion() {
        return aplicacion;
    }

    public void setAplicacion(JFrame aplicacion) {
        this.aplicacion = aplicacion;
        dialogoDatos.setLocationRelativeTo(aplicacion);
        dialogoEliminar.setLocationRelativeTo(aplicacion);
        dialogoModificar.setLocationRelativeTo(aplicacion);
        dialogoDatosEmpresa.setLocationRelativeTo(aplicacion);
    }

    public JButton getBtnSeleccionar() {
        return btnSeleccionar;
    }

    public void setBtnSeleccionar(JButton btnSeleccionar) {
        this.btnSeleccionar = btnSeleccionar;
    }

    public JButton getBtnDatos() {
        return btnDatos;
    }

    public void setBtnDatos(JButton btnDatos) {
        this.btnDatos = btnDatos;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnModCli() {
        return btnModCli;
    }

    public void setBtnModCli(JButton btnModCli) {
        this.btnModCli = btnModCli;
    }

    public JDialog getCentrarEnDialogo() {
        return CentrarEnDialogo;
    }

    public void setCentrarEnDialogo(JDialog CentrarEnDialogo) {
        this.CentrarEnDialogo = CentrarEnDialogo;
        dialogoDatos.setLocationRelativeTo(CentrarEnDialogo);
        dialogoEliminar.setLocationRelativeTo(CentrarEnDialogo);
        dialogoModificar.setLocationRelativeTo(CentrarEnDialogo);
        dialogoDatosEmpresa.setLocationRelativeTo(CentrarEnDialogo);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel boxCliente;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnDatosAceptar;
    private javax.swing.JButton btnDatosEmpresaAceptar;
    private javax.swing.JButton btnDigAceptar;
    private javax.swing.JButton btnDigCancelar;
    private javax.swing.JButton btnDigCancelar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnHideAlquiler;
    private javax.swing.JButton btnHideAlquileres;
    private javax.swing.JButton btnModAceptar;
    private javax.swing.JButton btnModCli;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JButton btnVerAlquilerParticular;
    private javax.swing.JButton btnVerAlquileresEmpresas;
    private javax.swing.JDialog dialogoDatos;
    private javax.swing.JDialog dialogoDatosEmpresa;
    private javax.swing.JDialog dialogoEliminar;
    private javax.swing.JDialog dialogoModificar;
    private javax.swing.JTextField entModApel;
    private javax.swing.JTextField entModDni;
    private javax.swing.JTextField entModEmail;
    private javax.swing.JTextField entModFechNac;
    private javax.swing.JTextField entModNombre;
    private javax.swing.JTextField entModPuntos;
    private javax.swing.JTextField entModTelf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lblApelData;
    private javax.swing.JLabel lblDataApel;
    private javax.swing.JLabel lblDataCif;
    private javax.swing.JLabel lblDataDni;
    private javax.swing.JLabel lblDataEdad;
    private javax.swing.JLabel lblDataEmail;
    private javax.swing.JLabel lblDataEmailEmpresa;
    private javax.swing.JLabel lblDataFecha;
    private javax.swing.JLabel lblDataNombre;
    private javax.swing.JLabel lblDataNombreEmpresa;
    private javax.swing.JLabel lblDataPuntos;
    private javax.swing.JLabel lblDataTelf;
    private javax.swing.JLabel lblDataTelfEmpresa;
    private javax.swing.JLabel lblDigDni;
    private javax.swing.JLabel lblDigEdad;
    private javax.swing.JLabel lblDigEmail;
    private javax.swing.JLabel lblDigNombre;
    private javax.swing.JLabel lblDigPuntos;
    private javax.swing.JLabel lblDigTelf;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblDniCli;
    private javax.swing.JLabel lblDniData;
    private javax.swing.JLabel lblDniData1;
    private javax.swing.JLabel lblDniEliminar;
    private javax.swing.JLabel lblEdadData;
    private javax.swing.JLabel lblEdadEliminar;
    private javax.swing.JLabel lblEmailData;
    private javax.swing.JLabel lblEmailData1;
    private javax.swing.JLabel lblEmailEliminar;
    private javax.swing.JLabel lblFechaData;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblModApel;
    private javax.swing.JLabel lblModDni;
    private javax.swing.JLabel lblModEmail;
    private javax.swing.JLabel lblModFechaNac;
    private javax.swing.JLabel lblModNombre;
    private javax.swing.JLabel lblModPuntos;
    private javax.swing.JLabel lblModTelefono;
    private javax.swing.JLabel lblNomCli;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreData;
    private javax.swing.JLabel lblNombreData1;
    private javax.swing.JLabel lblNombreEliminar;
    private javax.swing.JLabel lblPuntosData;
    private javax.swing.JLabel lblPuntosEliminar;
    private javax.swing.JLabel lblTelfData;
    private javax.swing.JLabel lblTelfData1;
    private javax.swing.JLabel lblTelfEliminar;
    private javax.swing.JPanel panelAlquiler;
    private javax.swing.JPanel panelAlquilerBox;
    private javax.swing.JPanel panelAlquileres;
    private javax.swing.JPanel panelAlquileresBox;
    // End of variables declaration//GEN-END:variables
}
